[package]
name = "bevy_oit"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
anyhow = "1.0.72"
bevy = "0.11"

[dev-dependencies]
dxf = "0.5.0"
nalgebra = "0.32.3"
rand = "0.8.5"
